# Generated by Django 5.2.3 on 2026-04-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0002_remove_student_course_remove_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='sn',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
