name: Full Stack CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        working-directory: appointment_system
        run: pip install -r requirements.txt

      - name: Run Django Tests
        working-directory: appointment_system
        run: python manage.py test
        
      - name: Run Frontend Tests
        working-directory: appointment_system/frontend
        run: npm install && npm test
